language: node_js
node_js:
  - '8.5'
services:
  - mongodb
env:
  - CXX=g++-4.8 PORT=8080 NODE_ENV='test' API_URL='http://localhost:3000' CLIENT_URL='http://localhost:8080' CORS_ORIGINS='http://localhost:3000'
sudo: required
before_script: npm i
script:
  - npm test
  - npm run travis-lint
notifications:
  email: false
